### PR TITLE
Added support for server port number.

### PR DESCRIPTION
**Pull request by cpitkin**
This is great work thank you. I was running into the issue of my server running ssh on a non standard port so I added support for it.

### CODE REVIEW

**Comment by andruschka** [comment]
Hello and thank you for the pull request! - I build this tool in :coffee: script - so I think I have to reimplement your changes in coffeescript.

**Comment by cpitkin** [comment]
If you want I can take a look at adding the coffee script myself. I am just a vanilla JS guy so it was easier for me to make the changes in JS. Give me a day or so and I can try it out if you want.

**Comment by andruschka** [comment]
I have you covered and implemented your changes in coffee allready - thank you!

**Comment by andruschka** [comment]
Available with next release (maybe this evening)

**Pull request closed without merging**
